// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gtk {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	[Flags]
	public enum JunctionSides {

		None,
		CornerTopleft = 1 << 0,
		CornerTopright = 1 << 1,
		CornerBottomleft = 1 << 2,
		CornerBottomright = 1 << 3,
		Top = CornerTopleft | CornerTopright,
		Bottom = CornerBottomleft | CornerBottomright,
		Left = CornerTopleft | CornerBottomleft,
		Right = CornerTopright | CornerBottomright,
	}
#endregion
}
